---
title: "Introduccion a la Dendrocronologia en R"
output: html_notebook
---
#### Clase intro a la Dendrocronologia

###### Instrucciones
bla bla 
bla bla

en cada seccion  podras  ejecutar y analizar   los comandos  basicos para  leer, visualisar y realizar  los analisis baicos utilizados en Dendrocronologia.  la mayoria de analisis que se llevaran acabo son iguales o muy similares a los que COFECHA y ARSTAN  pueden ejecutar. En este caso utilizaremos el  ambiente de R y utilizaremso  el paquete dplR  programado y desarrollado por Andy Bunn y Mikko Korpela 2014 (https://drive.google.com/uc?export=download&id=1ps7tZ0RTwuIr2P_h-ugHkbgAs3Jrdxaa)

La idea de estos ejercicios es que puedas familiarizarte con este tipo de ambiente, y  puedas aprender haciendo....


`rm(list=ls())` esto borrara  todos los objetos que tengan activos en R es bueno comenzar en blanco para evitar problemas cuando nombramos algun objeto

A continuacion vamos a instalr y activar el dplR y se conectaran a la base de datos del ITRDB mediante la web

```{r}
#install.packages(dplR)
library(dplR) # libreria para analisis dendrocronologicos
Dat_web <- read.rwl("https://www.ncei.noaa.gov/pub/data/paleo/treering/measurements/northamerica/mexico/mexi042.rwl")
Dat_ftp <- read.rwl("ftp://ftp.ncdc.noaa.gov/pub/data/paleo/treering/measurements/northamerica/mexico/mexi042.rwl")
Dat_web[,11]==Dat_ftp[,11]
str(Dat_ftp) # str te da la estructura del objeto llamado Datos
str(Dat_web) # str te da la estructura del objeto llamado Datos
```

